### ISSUE TITLE
Crashes with latest Python3.6 and Django

### ISSUE THREAD

**Issue by kayhayen** [collinmutembei/django-background-tasks-example#6]
This is what I have:

```
Django==2.0.4
django-background-tasks==1.1.13
django-compat==1.0.15
```

And doing runserver with python3.6 does this:

```
erforming system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa0694ed840>
Traceback (most recent call last):
  File "/opt/python363/lib/python3.6/site-packages/django/urls/conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python363/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/opt/python363/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/opt/python363/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/python363/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/python363/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/python363/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/opt/python363/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/opt/python363/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/python363/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/python363/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/python363/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/python363/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hayen/repos/django-background-tasks-example/project/project/urls.py", line 20, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/opt/python363/lib/python3.6/site-packages/django/urls/conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
```

**Comment by davidzwa** [comment]
It's quite simple to fix: uncomment the admin urls include or fix the tuple exception by hand. It's a Django 2 problem
<pre>url('admin/', admin.site.urls),
</pre>

**Comment by collinmutembei** [comment]
@kayhayen Pardon the delayed response. Hope you managed to resolve the issue with running the project. If not, the issue you experienced has to do with the Django version you used to run this test project (`2.0.4`). There were some backward incompatible changes on URL routing syntax introduced from Django [`2.0`](https://docs.djangoproject.com/en/2.0/releases/2.0/#what-s-new-in-django-2-0). I'll be making updates to support running the latest version of Django in due time.

**Comment by kayhayen** [comment]
@collinmutembei Thanks a lot, I will retry :)
